language: ruby
cache: bundler

before_script:
  - gem install bundler -v '~> 1.17.0'
  - bundle install --deployment
  - bin/rake db:setup

services:
  - elasticsearch
  - postgresql

env:
  DATABASE_URL=postgres://postgres@127.0.0.1/ruby_api

script: bin/rake test
