yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@babel/preset-env@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-syntax-dynamic-import@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-destructuring@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-proposal-class-properties@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-proposal-object-rest-spread@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-runtime@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-regenerator@*":
    dependencies:
      "@babel/core": "*"
  "monaco-editor@*":
    dependencies:
      "@babel/runtime": "*"
  "webpack-dev-server@*":
    dependencies:
      "webpack": "^4.0.0"
  "webpack-dev-middleware@*":
    dependencies:
      "webpack": "^4.0.0"
  "monaco-editor-webpack-plugin@*":
    dependencies:
      "webpack": "*"
  "postcss-cssnext@*":
    dependencies:
      "caniuse-lite": "*"
  "@stimulus/core@*":
    dependencies:
      "@stimulus/multimap": "*"