name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'

env:
  BUNDLE_PATH: vendor/bundle

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Run linting
        run: ./bin/standardrb --no-fix

  test-import:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.3.2
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
        options: >-
          --health-cmd "curl --silent --fail localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test Importing Ruby Documentation
        env:
          ELASTICSEARCH_URL: "http://localhost:9200"
        run: ./bin/rake "import:ruby[dev]"

  test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.3.2
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
        options: >-
          --health-cmd "curl --silent --fail localhost:9200/_cluster/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get -yqq install chromium-chromedriver
          yarn install --immutable

      - name: Compile Assets
        run: bundle exec rake webpacker:compile

      - name: Run Tests
        env:
          ELASTICSEARCH_URL: "http://localhost:9200"
        run: ./bin/rake test
